export default {
        "id": "1",
        "describe": "覆盖500万",
        "endDate": "2020-03-18",
        "parentOId": null,
        "companyOFlag": 1,
        "score": 70,
        "progressRate": 75,
        "completedTime": null,
        "createUserId": "1a18b5b1362b42a2a7228a9b171ab42a",
        "createTime": "2020-03-18 23:04:21",
        "createUserName": null,
        "createUserFlag": 2,
        "statusType": 1,
        "keyResultList": null,
        "childObjectiveList": [
            {
                "id": "8d83c343b2f54960bfe7143fe0c54b95",
                "describe": "呃呃呃呃呃",
                "endDate": "2020-03-27",
                "parentOId": "1",
                "companyOFlag": 2,
                "score": 70,
                "progressRate": 40,
                "completedTime": null,
                "createUserId": "1a18b5b1362b42a2a7228a9b171ab42a",
                "createTime": "2020-03-19 18:03:17",
                "createUserName": null,
                "createUserFlag": 2,
                "statusType": 1,
                "keyResultList": null,
                "childObjectiveList": [
                    {
                        "id": "420f795ab1ac43f39af500500a3be95f",
                        "describe": "有有有有有有有有有有",
                        "endDate": "2020-03-27",
                        "parentOId": "8d83c343b2f54960bfe7143fe0c54b95",
                        "companyOFlag": 2,
                        "score": null,
                        "progressRate": 0,
                        "completedTime": null,
                        "createUserId": "1a18b5b1362b42a2a7228a9b171ab42a",
                        "createTime": "2020-03-19 18:07:38",
                        "createUserName": null,
                        "createUserFlag": 2,
                        "statusType": 1,
                        "keyResultList": null,
                        "childObjectiveList": null,
                        "parentObjectiveModel": null,
                        "deleteFlag": 2
                    },
                    {
                        "id": "65323ca57b1c49309a1a1976b3afca18",
                        "describe": "日日日日日日日日日日",
                        "endDate": "2020-04-19",
                        "parentOId": "8d83c343b2f54960bfe7143fe0c54b95",
                        "companyOFlag": 2,
                        "score": null,
                        "progressRate": 0,
                        "completedTime": null,
                        "createUserId": "1a18b5b1362b42a2a7228a9b171ab42a",
                        "createTime": "2020-03-19 18:07:52",
                        "createUserName": null,
                        "createUserFlag": 2,
                        "statusType": 1,
                        "keyResultList": null,
                        "childObjectiveList": null,
                        "parentObjectiveModel": null,
                        "deleteFlag": 2
                    }
                ],
                "parentObjectiveModel": null,
                "deleteFlag": 2
            },
            {
                "id": "e09f90bd013543fd9f6a67ed54d62c80",
                "describe": "哇哇哇哇哇",
                "endDate": "2020-03-31",
                "parentOId": "1",
                "companyOFlag": 2,
                "score": null,
                "progressRate": 0,
                "completedTime": null,
                "createUserId": "1a18b5b1362b42a2a7228a9b171ab42a",
                "createTime": "2020-03-19 18:04:11",
                "createUserName": null,
                "createUserFlag": 2,
                "statusType": 1,
                "keyResultList": null,
                "childObjectiveList": [
                    {
                        "id": "0e09f8d9126a46b2a714e63e2ba1931c",
                        "describe": "踩踩踩踩踩踩踩踩踩",
                        "endDate": "2020-03-31",
                        "parentOId": "e09f90bd013543fd9f6a67ed54d62c80",
                        "companyOFlag": 2,
                        "score": null,
                        "progressRate": 0,
                        "completedTime": null,
                        "createUserId": "1a18b5b1362b42a2a7228a9b171ab42a",
                        "createTime": "2020-03-19 18:05:47",
                        "createUserName": null,
                        "createUserFlag": 2,
                        "statusType": 1,
                        "keyResultList": null,
                        "childObjectiveList": null,
                        "parentObjectiveModel": null,
                        "deleteFlag": 2
                    },
                    {
                        "id": "f62874a540094f609dd4bd1d1dcf30fb",
                        "describe": "她她她她她她她",
                        "endDate": "2020-03-31",
                        "parentOId": "e09f90bd013543fd9f6a67ed54d62c80",
                        "companyOFlag": 2,
                        "score": null,
                        "progressRate": 0,
                        "completedTime": null,
                        "createUserId": "1a18b5b1362b42a2a7228a9b171ab42a",
                        "createTime": "2020-03-19 18:06:10",
                        "createUserName": null,
                        "createUserFlag": 2,
                        "statusType": 1,
                        "keyResultList": null,
                        "childObjectiveList": null,
                        "parentObjectiveModel": null,
                        "deleteFlag": 2
                    },
                    {
                        "id": "9709f07e8296401e99039f056e906b6b",
                        "describe": "哈哈哈哈哈哈哈哈哈哈哈",
                        "endDate": "2020-03-28",
                        "parentOId": "e09f90bd013543fd9f6a67ed54d62c80",
                        "companyOFlag": 2,
                        "score": null,
                        "progressRate": 0,
                        "completedTime": null,
                        "createUserId": "3ad5433a22a941e698d31d5ab4220729",
                        "createTime": "2020-03-24 17:33:02",
                        "createUserName": null,
                        "createUserFlag": 1,
                        "statusType": 1,
                        "keyResultList": null,
                        "childObjectiveList": null,
                        "parentObjectiveModel": null,
                        "deleteFlag": 2
                    }
                ],
                "parentObjectiveModel": null,
                "deleteFlag": 2
            },
            {
                "id": "48f33007b9834f1dacf5f7c10bd2d5f9",
                "describe": "帆帆帆帆",
                "endDate": "2020-03-26",
                "parentOId": "1",
                "companyOFlag": 2,
                "score": null,
                "progressRate": 0,
                "completedTime": null,
                "createUserId": "1a18b5b1362b42a2a7228a9b171ab42a",
                "createTime": "2020-03-19 18:04:29",
                "createUserName": null,
                "createUserFlag": 2,
                "statusType": 1,
                "keyResultList": null,
                "childObjectiveList": [
                    {
                        "id": "f83562bdb49248449664ea7d7986e5ce",
                        "describe": "红红火火恍恍惚惚",
                        "endDate": "2020-03-27",
                        "parentOId": "48f33007b9834f1dacf5f7c10bd2d5f9",
                        "companyOFlag": 2,
                        "score": null,
                        "progressRate": 0,
                        "completedTime": null,
                        "createUserId": "1a18b5b1362b42a2a7228a9b171ab42a",
                        "createTime": "2020-03-19 18:06:43",
                        "createUserName": null,
                        "createUserFlag": 2,
                        "statusType": 1,
                        "keyResultList": null,
                        "childObjectiveList": null,
                        "parentObjectiveModel": null,
                        "deleteFlag": 2
                    },
                    {
                        "id": "428f4c3da27947159e1e1697999d0e25",
                        "describe": "iiiiiiiiiiiiiiiiiiiiiiiii",
                        "endDate": "2020-03-28",
                        "parentOId": "48f33007b9834f1dacf5f7c10bd2d5f9",
                        "companyOFlag": 2,
                        "score": null,
                        "progressRate": 0,
                        "completedTime": null,
                        "createUserId": "1a18b5b1362b42a2a7228a9b171ab42a",
                        "createTime": "2020-03-19 18:07:00",
                        "createUserName": null,
                        "createUserFlag": 2,
                        "statusType": 1,
                        "keyResultList": null,
                        "childObjectiveList": null,
                        "parentObjectiveModel": null,
                        "deleteFlag": 2
                    }
                ],
                "parentObjectiveModel": null,
                "deleteFlag": 2
            },
            {
                "id": "f6eadd91ae9342e2b239789264675f64",
                "describe": "测试",
                "endDate": "2020-03-27",
                "parentOId": "1",
                "companyOFlag": 1,
                "score": 70,
                "progressRate": 6.666666666666666,
                "completedTime": null,
                "createUserId": "3ad5433a22a941e698d31d5ab4220729",
                "createTime": "2020-03-20 14:12:38",
                "createUserName": null,
                "createUserFlag": 1,
                "statusType": 1,
                "keyResultList": null,
                "childObjectiveList": [
                    {
                        "id": "e639051655534b04b7860077d156902b",
                        "describe": "她她她她她她",
                        "endDate": "2020-03-27",
                        "parentOId": "f6eadd91ae9342e2b239789264675f64",
                        "companyOFlag": 2,
                        "score": null,
                        "progressRate": 0,
                        "completedTime": null,
                        "createUserId": "3ad5433a22a941e698d31d5ab4220729",
                        "createTime": "2020-03-23 11:39:46",
                        "createUserName": null,
                        "createUserFlag": 1,
                        "statusType": 1,
                        "keyResultList": null,
                        "childObjectiveList": null,
                        "parentObjectiveModel": null,
                        "deleteFlag": 2
                    },
                    {
                        "id": "65fffa4b7bd447888c8d3edf70f5b0f3",
                        "describe": "红火火恍恍惚惚",
                        "endDate": "2020-03-27",
                        "parentOId": "f6eadd91ae9342e2b239789264675f64",
                        "companyOFlag": 2,
                        "score": null,
                        "progressRate": 0,
                        "completedTime": null,
                        "createUserId": "3ad5433a22a941e698d31d5ab4220729",
                        "createTime": "2020-03-23 11:40:49",
                        "createUserName": null,
                        "createUserFlag": 1,
                        "statusType": 1,
                        "keyResultList": null,
                        "childObjectiveList": [
                            {
                                "id": "3d420b06cbcf4362996fb372097d8953",
                                "describe": "ffffffffffffffffff",
                                "endDate": "2020-03-26",
                                "parentOId": "65fffa4b7bd447888c8d3edf70f5b0f3",
                                "companyOFlag": 2,
                                "score": null,
                                "progressRate": 0,
                                "completedTime": null,
                                "createUserId": "3ad5433a22a941e698d31d5ab4220729",
                                "createTime": "2020-03-24 09:47:48",
                                "createUserName": null,
                                "createUserFlag": 1,
                                "statusType": 1,
                                "keyResultList": null,
                                "childObjectiveList": null,
                                "parentObjectiveModel": null,
                                "deleteFlag": 2
                            }
                        ],
                        "parentObjectiveModel": null,
                        "deleteFlag": 2
                    },
                    {
                        "id": "a53e8c283fb04126997dc6556c0a1ef5",
                        "describe": "v啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵啵",
                        "endDate": "2020-03-28",
                        "parentOId": "f6eadd91ae9342e2b239789264675f64",
                        "companyOFlag": 2,
                        "score": null,
                        "progressRate": 0,
                        "completedTime": null,
                        "createUserId": "3ad5433a22a941e698d31d5ab4220729",
                        "createTime": "2020-03-23 12:49:10",
                        "createUserName": null,
                        "createUserFlag": 1,
                        "statusType": 1,
                        "keyResultList": null,
                        "childObjectiveList": null,
                        "parentObjectiveModel": null,
                        "deleteFlag": 2
                    }
                ],
                "parentObjectiveModel": null,
                "deleteFlag": 2
            },
            {
                "id": "c88ad3d9a19346a1ae5e535ecc648ada",
                "describe": "顶顶顶顶顶顶顶顶顶顶顶",
                "endDate": "2020-03-31",
                "parentOId": "1",
                "companyOFlag": 2,
                "score": null,
                "progressRate": 0,
                "completedTime": null,
                "createUserId": "3ad5433a22a941e698d31d5ab4220729",
                "createTime": "2020-03-23 10:24:34",
                "createUserName": null,
                "createUserFlag": 1,
                "statusType": 1,
                "keyResultList": null,
                "childObjectiveList": [
                    {
                        "id": "e19e43b4b105472faeb7845b8d2b9b34",
                        "describe": "灌灌灌灌",
                        "endDate": "2020-03-28",
                        "parentOId": "c88ad3d9a19346a1ae5e535ecc648ada",
                        "companyOFlag": 2,
                        "score": null,
                        "progressRate": 0,
                        "completedTime": null,
                        "createUserId": "3ad5433a22a941e698d31d5ab4220729",
                        "createTime": "2020-03-23 11:41:11",
                        "createUserName": null,
                        "createUserFlag": 1,
                        "statusType": 1,
                        "keyResultList": null,
                        "childObjectiveList": [
                            {
                                "id": "09e77ffd675649db8ed10568facb4c91",
                                "describe": "呃呃呃呃呃呃呃呃呃呃呃呃呃",
                                "endDate": "2020-03-24",
                                "parentOId": "e19e43b4b105472faeb7845b8d2b9b34",
                                "companyOFlag": 2,
                                "score": null,
                                "progressRate": 0,
                                "completedTime": null,
                                "createUserId": "3ad5433a22a941e698d31d5ab4220729",
                                "createTime": "2020-03-24 17:32:14",
                                "createUserName": null,
                                "createUserFlag": 1,
                                "statusType": 1,
                                "keyResultList": null,
                                "childObjectiveList": null,
                                "parentObjectiveModel": null,
                                "deleteFlag": 2
                            }
                        ],
                        "parentObjectiveModel": null,
                        "deleteFlag": 2
                    }
                ],
                "parentObjectiveModel": null,
                "deleteFlag": 2
            }
        ],
        "parentObjectiveModel": null,
        "deleteFlag": 2
    }
